[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  VITE_SUPABASE_URL = "https://ekkxvtzrufhzhodvoeei.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY0MTI0ODAyNCwiZXhwIjoxOTU2ODI0MDI0fQ.eOSskmjSmjYO4xp_4l8CvixrHmMoHnFr9PNRwEdf5Y4"
  SUPABASE_PRIVATE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjQxMjQ4MDI0LCJleHAiOjE5NTY4MjQwMjR9.amFdmr3mUy5Nnqg4H4vbpqj2F8ZNpCm5LFmbNg2YFcE"
  SUPABASE_JWT_SECRET = "46833cf3-706c-4374-aeb3-07fedb836fd3"